server:
  port: 9092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testa_sdb
    username: testa
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: User Management
  jpa:
    hibernate:
      ddl-auto : none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        jdbc:
#          lob:
#            non_contextual_creation: true
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace